// export const ADD_SUBSCRIBER = 'ADD_SUBSCRIBER'
// export const REMOVE_SUBSCRIBER = 'REMOVE_SUBSCRIBER'

export const DASHBOARD_ADD = 'DASHBOARD_ADD'
export const DASHBOARD_REMOVE = 'DASHBOARD_REMOVE'
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE'